package main

import (
	"bytes"
	"context"
	"crypto/ed25519"
	"crypto/x509"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os/exec"
	"strings"
	"testing"
	"time"

	application "github.com/generalbusiness-ai/gitseq-chess"
)

func TestGameDraftWebCryptoSigningParity(t *testing.T) {
	ctx := context.Background()
	repo, white, ws := newIdentityTestRepository(t, ctx)
	created, err := application.Create(ctx, ws, white, "white", "", "", "webcrypto")
	if err != nil {
		t.Fatal(err)
	}
	public, key := generateIdentityKey(t)
	h := newReadHandler(ctx, repo)
	var draft preparedGameResponse
	postJSON(t, h, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: created.ID, ActorKey: public}, &draft, 200)
	pkcs8, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		t.Fatal(err)
	}
	fixture, err := json.Marshal(map[string]any{"prepared": draft, "expected": draft.Echo, "private": pkcs8, "public": public, "signature": ed25519.Sign(key, draft.SigningBytes)})
	if err != nil {
		t.Fatal(err)
	}
	// Exercise the actual UI echo guard and WebCrypto over host-generated bytes.
	// The imported test-only private key is nonexportable, like the tab key.
	const script = `
const { webcrypto } = require('node:crypto');
const { checkedGameDraft } = require('./ui/app.js');
const f = JSON.parse(require('node:fs').readFileSync(0, 'utf8'));
(async () => {
  const bytes = Buffer.from(checkedGameDraft(f.prepared, f.expected, Math.floor(Date.now() / 1000)), 'base64');
  const key = await webcrypto.subtle.importKey('pkcs8', Buffer.from(f.private, 'base64'), 'Ed25519', false, ['sign']);
  const signature = Buffer.from(await webcrypto.subtle.sign('Ed25519', key, bytes));
  if (signature.toString('base64') !== f.signature) throw Error('Go/WebCrypto signature mismatch');
  let refused = false;
  try { await webcrypto.subtle.exportKey('pkcs8', key); } catch { refused = true; }
  if (!refused) throw Error('private key exported');
  process.stdout.write(JSON.stringify({signature: signature.toString('base64')}));
})().catch(error => { console.error(error); process.exitCode = 1; });`
	cmd := exec.CommandContext(ctx, "node", "-e", script)
	cmd.Stdin = bytes.NewReader(fixture)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("WebCrypto fixture: %v\n%s", err, output)
	}
	var signed struct{ Signature []byte }
	if err := json.Unmarshal(output, &signed); err != nil {
		t.Fatal(err)
	}
	var result map[string]any
	postJSON(t, h, "/v1/actions/submit", identitySubmitRequest{Draft: draft.Draft, ActorKey: public, ActorSignature: signed.Signature}, &result, 200)
	if result["effective"] != true {
		t.Fatalf("WebCrypto-signed join refused: %#v", result)
	}
}

type preparedGameResponse struct {
	Draft        string         `json:"draft"`
	SigningBytes []byte         `json:"signing_bytes"`
	Echo         gameActionEcho `json:"echo"`
	Expires      int64          `json:"expires"`
}

func submitGameTest(t *testing.T, h http.Handler, d preparedGameResponse, key ed25519.PrivateKey) map[string]any {
	t.Helper()
	var result map[string]any
	postJSON(t, h, "/v1/actions/submit", identitySubmitRequest{Draft: d.Draft, ActorKey: key.Public().(ed25519.PublicKey), ActorSignature: ed25519.Sign(key, d.SigningBytes)}, &result, 200)
	return result
}

func TestBrowserGameJoinRaceMoveAndExactRetry(t *testing.T) {
	ctx := context.Background()
	repo, white, ws := newIdentityTestRepository(t, ctx)
	create, err := application.Create(ctx, ws, white, "white", "", "", "game")
	if err != nil {
		t.Fatal(err)
	}
	h := newReadHandler(ctx, repo)
	blackPublic, black := generateIdentityKey(t)
	otherPublic, other := generateIdentityKey(t)
	var join, loser preparedGameResponse
	postJSON(t, h, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: create.ID, ActorKey: blackPublic}, &join, 200)
	postJSON(t, h, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: create.ID, ActorKey: otherPublic}, &loser, 200)
	if join.Echo.Game != create.ID || join.Echo.Actor != liveFingerprint(blackPublic) || join.Echo.Action != "join" {
		t.Fatal("wrong action echo")
	}
	if got := submitGameTest(t, h, join, black); got["effective"] != true {
		t.Fatalf("join: %#v", got)
	}
	if got := submitGameTest(t, h, loser, other); got["effective"] != false || got["reason"] == nil {
		t.Fatalf("join race: %#v", got)
	}
	_, projection, err := application.OpenProjection(ctx, repo)
	if err != nil {
		t.Fatal(err)
	}
	game, _ := projection.GameByID(create.ID)
	var first, stale preparedGameResponse
	for _, pair := range []struct {
		move string
		out  *preparedGameResponse
	}{{"e2e4", &first}, {"d2d4", &stale}} {
		postJSON(t, h, "/v1/actions/prepare", gameActionRequest{Action: "move", Game: create.ID, Move: pair.move, Predecessor: game.LastMove, ActorKey: white.Public().(ed25519.PublicKey)}, pair.out, 200)
	}
	before, err := ws.Records(ctx)
	if err != nil {
		t.Fatal(err)
	}
	invalid := ed25519.Sign(white, first.SigningBytes)
	invalid[0] ^= 1
	postJSON(t, h, "/v1/actions/submit", identitySubmitRequest{Draft: first.Draft, ActorKey: white.Public().(ed25519.PublicKey), ActorSignature: invalid}, nil, 400)
	postJSON(t, h, "/v1/actions/submit", identitySubmitRequest{Draft: first.Draft, ActorKey: blackPublic, ActorSignature: ed25519.Sign(black, first.SigningBytes)}, nil, 400)
	unchanged, err := ws.Records(ctx)
	if err != nil || unchanged.Depth != before.Depth {
		t.Fatal("invalid signature/actor appended")
	}
	result := submitGameTest(t, h, first, white)
	if result["effective"] != true {
		t.Fatalf("move: %#v", result)
	}
	retry := submitGameTest(t, h, first, white)
	if retry["record"] != result["record"] || retry["depth"] != result["depth"] {
		t.Fatalf("retry changed record count: %#v %#v", result, retry)
	}
	if got := submitGameTest(t, h, stale, white); got["effective"] != false || got["reason"] == nil {
		t.Fatalf("stale move: %#v", got)
	}
	after, err := ws.Records(ctx)
	if err != nil || after.Depth != before.Depth+2 {
		t.Fatalf("depth after exact retries and stale move: %#v %v", after, err)
	}
	postJSON(t, h, "/v1/actions/prepare", gameActionRequest{Action: "move", Game: create.ID, Move: "e7e5", Predecessor: game.LastMove, ActorKey: blackPublic}, nil, 409)
}

func TestGameDraftBoundsAndExpiry(t *testing.T) {
	ctx := context.Background()
	repo, white, ws := newIdentityTestRepository(t, ctx)
	create, err := application.Create(ctx, ws, white, "white", "", "", "game")
	if err != nil {
		t.Fatal(err)
	}
	service := newGameActionsHTTP(repo)
	now := time.Now()
	service.now = func() time.Time { return now }
	mux := http.NewServeMux()
	service.register(mux)
	handler := trustedLiveHost(rejectLiveQueries(mux))
	public, key := generateIdentityKey(t)
	var first preparedGameResponse
	postJSON(t, handler, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: create.ID, ActorKey: public}, &first, 200)
	// Fill the bounded store directly: the admission path must refuse before
	// opening the repository, and expiry must reclaim completed and pending slots.
	for len(service.drafts) < maxGameDrafts {
		service.drafts[strings.Repeat("x", len(service.drafts))] = &gameActionDraft{expires: now.Add(gameDraftTTL)}
	}
	postJSON(t, handler, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: create.ID, ActorKey: public}, nil, 429)
	now = now.Add(gameDraftTTL)
	postJSON(t, handler, "/v1/actions/submit", identitySubmitRequest{Draft: first.Draft, ActorKey: public, ActorSignature: ed25519.Sign(key, first.SigningBytes)}, nil, 400)
	if len(service.drafts) != 0 {
		t.Fatal("expired draft slots retained")
	}
	var next preparedGameResponse
	postJSON(t, handler, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: create.ID, ActorKey: public}, &next, 200)
	postJSON(t, handler, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: create.ID, ActorKey: public, Secret: strings.Repeat("s", 8<<10)}, nil, 400)
	postJSON(t, handler, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: create.ID, ActorKey: public, Secret: strings.Repeat("s", 32<<10)}, nil, 400)
	postJSON(t, handler, "/v1/actions/prepare?secret=leak", gameActionRequest{Action: "join", Game: create.ID, ActorKey: public}, nil, 400)
}

func TestGameDraftCannotChangeGameOrSurviveRestart(t *testing.T) {
	ctx := context.Background()
	repo, white, ws := newIdentityTestRepository(t, ctx)
	public, key := generateIdentityKey(t)
	h := newReadHandler(ctx, repo)
	var drafts [2]preparedGameResponse
	for i := range drafts {
		game, err := application.Create(ctx, ws, white, "white", "", "", "game-"+string(rune('a'+i)))
		if err != nil {
			t.Fatal(err)
		}
		postJSON(t, h, "/v1/actions/prepare", gameActionRequest{Action: "join", Game: game.ID, ActorKey: public}, &drafts[i], 200)
	}
	signature := ed25519.Sign(key, drafts[0].SigningBytes)
	before, err := ws.Records(ctx)
	if err != nil {
		t.Fatal(err)
	}
	postJSON(t, h, "/v1/actions/submit", identitySubmitRequest{Draft: drafts[1].Draft, ActorKey: public, ActorSignature: signature}, nil, 400)
	postJSON(t, h, "/v1/actions/submit", map[string]any{"draft": drafts[0].Draft, "actor_key": public, "actor_signature": signature, "game": drafts[1].Echo.Game}, nil, 400)
	postJSON(t, newReadHandler(ctx, repo), "/v1/actions/submit", identitySubmitRequest{Draft: drafts[0].Draft, ActorKey: public, ActorSignature: signature}, nil, 400)
	after, err := ws.Records(ctx)
	if err != nil || after.Depth != before.Depth {
		t.Fatal("changed game or unknown restarted draft appended")
	}
}

func TestGameActionOriginGuards(t *testing.T) {
	// A sentinel downstream proves the guard refused before parsing or custody.
	for _, path := range []string{"/v1/actions/prepare", "/v1/actions/submit"} {
		for _, test := range []struct{ name, host, origin, site, content string }{
			{"host", "attacker.invalid", "", "", "application/json"},
			{"origin", "127.0.0.1:8080", "http://attacker.invalid", "", "application/json"},
			{"site", "127.0.0.1:8080", "", "cross-site", "application/json"},
			{"content", "127.0.0.1:8080", "", "", "text/plain"},
		} {
			t.Run(path+"/"+test.name, func(t *testing.T) {
				h := trustedLiveHost(http.HandlerFunc(func(http.ResponseWriter, *http.Request) { t.Fatal("untrusted action reached custody") }))
				r := httptest.NewRequest("POST", path, strings.NewReader("{}"))
				r.Host = test.host
				r.Header.Set("Origin", test.origin)
				r.Header.Set("Sec-Fetch-Site", test.site)
				r.Header.Set("Content-Type", test.content)
				w := httptest.NewRecorder()
				h.ServeHTTP(w, r)
				if w.Code != 400 {
					t.Fatalf("status %d", w.Code)
				}
			})
		}
	}
}
